name: linux_security_vulns

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: America/New_York
  ACTIONS_STEP_DEBUG: true

jobs:
  build-kernel:
    if: ${{ github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'kernel' || github.event.inputs.build_type == '' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: OLK-6.6
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-26.09
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-25.03
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-23.09
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-22.09
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-22.03-LTS-SP2
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-22.03-LTS-SP1
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-22.03-LTS
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-21.09
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-21.03
          - set_kernelrepourl: https://atomgit.com/openeuler/kernel
            set_branch: openEuler-20.09
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Show environment
        id: basic_info
        run: |
          nproc
          uname -a
          cat /etc/*release
          free -h
          mount
          df -h
          cat /proc/cpuinfo
          cat /proc/meminfo

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th

      - name: Run Kernel Build in Ubuntu 22.04 container
        working-directory: /builder
        run: |
          pwd
          sudo /bin/cp -a ${{ github.workspace }}/* .
          ls -alh
          sudo docker run --rm \
            --privileged \
            --cap-add SYS_ADMIN \
            -v /dev:/dev \
            -v /builder:/workspace \
            -w /workspace \
            ubuntu:22.04 \
            bash -c "
              chmod +x /workspace/kdevbuild/linux_security_vulns.sh ;
              /workspace/kdevbuild/linux_security_vulns.sh ${{ matrix.set_kernelrepourl }} ${{ matrix.set_branch }}
            "

      - name: List build output
        run: |
          ls -alh  /builder/release/*
          md5sum /builder/release/*

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        with:
          tag: kernel_cve
          artifacts: /builder/release/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: | # linux_security_vulns

            ## 发布内容
            - **Report** - kernel cve repo

            ## 免责声明
            - **按原样提供**：镜像不作任何保证，使用风险自负

